name: CHECK PR LABEL

on:
  workflow_call:
    outputs:
      debug:
        description: "firebase app distribution 배포용 라벨"
        value: ${{jobs.check_pr_label.outputs.debug}}


jobs:
  check_pr_label:
    runs-on: ubuntu-latest
    outputs:
      debug: ${{steps.check_pr_label.outputs.DEBUG}}
    steps:
      - id: check_pr_label
        name: check_pr_label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        shell: bash
        run: |
          # 해당 PR의 라벨을 가져온다
          pull_request_labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          echo "$pull_request_labels"
          
          # deploy-to-qa Label이 붙어 있는지 확인한다.
          if echo "$pull_request_labels" | grep -q '^app-destribution-debug$' ; then
          echo "APP-DESTRIBUTION-DEBUG=true" >> "$GITHUB_OUTPUT"
          fi

